#!/bin/sh
set -eu

REPO_ROOT=$(git rev-parse --show-toplevel)
BRANCH=$(git rev-parse --abbrev-ref HEAD)
COMMIT=$(git rev-parse --short HEAD)
BASE_BRANCH=${TAB_BEACON_REVIEW_BASE_BRANCH:-main}
UPDATED_AT=$(git show -s --format=%cI HEAD)

json_escape() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

BRANCH_ESCAPED=$(json_escape "$BRANCH")
COMMIT_ESCAPED=$(json_escape "$COMMIT")
BASE_ESCAPED=$(json_escape "$BASE_BRANCH")
UPDATED_AT_ESCAPED=$(json_escape "$UPDATED_AT")

mkdir -p "$REPO_ROOT/generated"

cat > "$REPO_ROOT/generated/review-build-info.local.js" <<EOF
// Auto-generated by githooks/update-review-build-info.sh
// Do not commit this file.
window.TabBeaconReviewTarget = {
  branch: "$BRANCH_ESCAPED",
  commit: "$COMMIT_ESCAPED",
  base: "$BASE_ESCAPED",
  updatedAt: "$UPDATED_AT_ESCAPED",
  source: "git-hooks"
};
EOF
